resources:
  MyAPI:
    type: api_gateway
    properties:
      name: my-api
      resources:
        proxy:
          path_part: "{proxy+}" 
          methods:
            ANY:
              integration:
                type: lambda
                lambda_function: MyLambdaFunction

  MyLambdaFunction:
    type: lambda
    properties:
      name: my-lambda
      handler: lambda_function.lambda_handler
      runtime: python3.10
      memory_size: 128
      timeout: 10
      policies:
        - AWSLambdaBasicExecutionRole
      function_url:
        auth_type: NONE 